theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

title: A crazy yellow theory
description: Projects by Dr D.D.
teaser: /images/hearts1.jpg

author:
  name: "Daniela Duca"
  avatar: "/docs/images/DD.jpg"
  bio: "PhD Product Manager, SAGE PUBLISHING." 
links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/danielagduca"
